# Generated by Django 4.2.7 on 2026-08-20 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated tags for search/filtering', max_length=255)),
                ('file', models.FileField(upload_to='projects/full/')),
                ('preview_file', models.FileField(blank=True, null=True, upload_to='projects/preview/')),
                ('price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('year_defended', models.PositiveIntegerField(default=2024, help_text='Year project was defended')),
                ('pages_count', models.PositiveIntegerField(blank=True, default=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='departments.department')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
